# Generated by Django 4.2.2 on 2023-07-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
